Use "embed" to store kubelet config template
openshift/windows-machine-config-bootstrapper pull request #295
Opened 2021-09-08 15:38 UTC by Fedosin

This commit starts using "embed" go module to store the template in the binary. It is easier and more natural than doing so with go-bindata.

2021-09-08 19:03 UTC, sebsoto requested changes
Thanks for the PR @Fedosin , I wasn't aware of the embed library.

2021-09-09 12:49 UTC, Fedosin commented on pkg/bootstrapper/bootstrapper.go
> +	f embed.FS
Done!

2021-09-09 13:39 UTC, saifshaikh48 reviewed
/lgtm

Thanks for working on this @Fedosin.

2021-09-09 13:43 UTC, mansikulkarni96 commented
/lgtm

2021-09-09 14:06 UTC, sebsoto commented
/approve

2021-09-09 14:08 UTC, merged

2021-09-09 17:16 UTC, aravindhp commented
/cherry-pick release-4.9
/cherry-pick release-4.8
/cherry-pick community-4.8

2021-09-10 05:08 UTC, mansikulkarni96 commented
/cherry-pick community-4.8

2021-09-10 05:08 UTC, mansikulkarni96 commented
/cherry-pick release-4.8