[OCPCLOUD-1247] Allow to override kubelet hostname
openshift/windows-machine-config-bootstrapper pull request #304
Opened 2021-10-26 13:18 UTC by Fedosin

This commit adds a new parameter for the bootstrapper: `--hostname`. It allows to define custom hostname for kubelet on the node.

It is required for deploying clusters on Windows machines with Cloud Controller Manager support, where hostnames must be the same as node names.

Related links:
https://issues.redhat.com/browse/OCPCLOUD-1247
https://bugzilla.redhat.com/show_bug.cgi?id=1995894

2021-11-09 14:50 UTC, JoelSpeed commented
For additional context, on some platforms (eg AWS, OpenStack), the default hostname of the instance (which is what Kubelet uses with `--cloud-provider=external`) does not match the node name which is given to kubelet by the in-tree cloud providers. To ensure we keep the node names consistent between in-tree and out-of-tree providers, we have used the `--hostname-override` flag on linux nodes by fetching data from the providers metadata services to grab the correct node name.

If we upgrade existing nodes and the node name changes between in-tree and out-of-tree, the Kubelet becomes broken as the client credentials renewal flow requests a name change, which is rejected by the CSR approval system within OpenShift. Equally, the kubelet would try to create a new Node object, orphaning the old Node. Therefore, we must keep the names consistent between in-tree and out-of-tree.

This PR is aiming to help us in that flow by allowing us to set the flag for the windows kubelets

2021-11-09 15:14 UTC, sebsoto requested changes
Thanks @Fedosin, looks mostly good, just some comments on the tests

2021-11-09 15:14 UTC, sebsoto commented on test/e2e/bootstrapper_test.go
> +			if argSplit[0] == "--hostname-override" {
If this test is only ran when the `hostname-override` argument is supposed to be set, I  would like to see this test fail if the `hostname-override` flag is missing

2021-11-09 15:14 UTC, sebsoto commented on test/e2e/bootstrapper_test.go
> +				assert.Equal(t, argSplit[1], "my-computer")
`my-computer` should either be an argument or a constant so it only needs to be maintained in one place

2021-11-11 14:52 UTC, Fedosin commented
/hold

2021-11-15 14:34 UTC, closed without merging