Remove empty space in kubelet_config.json
openshift/windows-machine-config-bootstrapper pull request #344
Opened 2022-03-22 21:03 UTC by jrvaldes

Fix the template field for clientCAFile in the kubelet_config.json, by
removing an empty space, causing kubelet to ignore the CA certificate file.

2022-03-22 21:11 UTC, alinaryan commented
/lgtm

2022-03-22 21:14 UTC, saifshaikh48 commented
/lgtm

2022-03-22 21:47 UTC, jrvaldes commented
/cherry-pick release-4.10

2022-03-22 21:47 UTC, jrvaldes commented
/cherry-pick release-4.9

2022-03-22 21:47 UTC, jrvaldes commented
/cherry-pick community-4.10

2022-03-22 21:47 UTC, jrvaldes commented
/cherry-pick community-4.9

2022-03-22 21:47 UTC, jrvaldes commented
/cherry-pick community-4.8

2022-03-22 21:50 UTC, jrvaldes commented
/assign @selansen

2022-03-23 02:24 UTC, selansen commented
certificate rotation is not a bug fix. I am fine with backporting it.

2022-03-23 02:26 UTC, selansen commented
/approve

2022-03-23 13:07 UTC, sebsoto commented
/lgtm

2022-03-23 13:08 UTC, sebsoto commented
/hold

2022-03-23 13:08 UTC, sebsoto commented
@jrvaldes held until cherry pick discussion resolved

2022-03-23 13:27 UTC, jrvaldes commented
/cherry-pick community-4.9 cancel

2022-03-23 13:47 UTC, jrvaldes commented
> @jrvaldes held until cherry pick discussion resolved

No backports. Deleted the /cherry-pick commands as per https://github.com/kubernetes/test-infra/issues/17174#issuecomment-622214376

2022-03-23 13:47 UTC, jrvaldes commented
/hold cancel

2022-03-23 14:59 UTC, saifshaikh48 commented
/lgtm

2022-03-23 15:12 UTC, aravindhp requested changes

2022-03-23 15:12 UTC, aravindhp commented on pkg/bootstrapper/bootstrapper_test.go
> +// cniTest holds the location of the directories and files required for running some of the CNI tests
Formatting  fixes shouldn't be done in a bug fix commit. This has been called out a few times.

2022-03-23 15:12 UTC, aravindhp commented on pkg/bootstrapper/bootstrapper_test.go
> +// }
Same here.

2022-03-23 15:38 UTC, aravindhp reviewed
LGTM

2022-03-23 15:41 UTC, saifshaikh48 commented
/lgtm

2022-03-23 19:22 UTC, jrvaldes commented
/test e2e-wmcb

Error: creating EC2 VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.

2022-03-23 20:54 UTC, jrvaldes commented
/hold

to investigate CI issue

2022-03-24 12:52 UTC, jrvaldes commented
/test e2e-wmcb

2022-03-24 12:52 UTC, jrvaldes commented
/test aws-e2e-ccm-install

2022-03-25 14:03 UTC, jrvaldes commented
/test e2e-wmcb

2022-03-25 14:05 UTC, jrvaldes commented
/test aws-e2e-ccm-install

2022-03-25 14:06 UTC, jrvaldes commented
/test e2e-wmcb

2022-03-28 19:23 UTC, jrvaldes commented
/test aws-e2e-ccm-install

2022-03-28 20:19 UTC, jrvaldes commented
/hold 

Still getting AWS quota  [issues](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-bootstrapper/344/pull-ci-openshift-windows-machine-config-bootstrapper-master-e2e-wmcb/1508522945788514304)

2022-03-29 15:11 UTC, jrvaldes commented
/test aws-e2e-ccm-install

2022-03-30 18:33 UTC, jrvaldes commented
/test e2e-wmcb

2022-03-30 19:55 UTC, jrvaldes commented
/test aws-e2e-ccm-install

2022-03-30 20:40 UTC, jrvaldes commented
/hold cancel

CI issues with the AWS quota limit is resolved.

2022-03-30 20:41 UTC, jrvaldes commented
/cherry-pick release-4.10

2022-03-30 20:41 UTC, jrvaldes commented
/cherry-pick community-4.10

2022-03-30 21:05 UTC, merged